### ISSUE TITLE
a40 failure

### ISSUE THREAD

**Issue by truatpasteurdotfr** [truatpasteurdotfr/singularity-docker-pytorch-a40#1]
`conda activate testgpu3;  python -c "import torch; print(torch.cuda.is_available()); print(torch.tensor([1.0, 2.0]).cuda())" `
```
True
/opt/conda/envs/testgpu3/lib/python3.6/site-packages/torch/cuda/__init__.py:104: UserWarning: 
A40 with CUDA capability sm_86 is not compatible with the current PyTorch installation.
The current PyTorch install supports CUDA capabilities sm_37 sm_50 sm_60 sm_70 sm_75.
If you want to use the A40 GPU with PyTorch, please check the instructions at https://pytorch.org/get-started/locally/

  warnings.warn(incompatible_device_warn.format(device_name, capability, " ".join(arch_list), device_name))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/envs/testgpu3/lib/python3.6/site-packages/torch/tensor.py", line 179, in __repr__
    return torch._tensor_str._str(self)
  File "/opt/conda/envs/testgpu3/lib/python3.6/site-packages/torch/_tensor_str.py", line 372, in _str
    return _str_intern(self)
  File "/opt/conda/envs/testgpu3/lib/python3.6/site-packages/torch/_tensor_str.py", line 352, in _str_intern
    tensor_str = _tensor_str(self, indent)
  File "/opt/conda/envs/testgpu3/lib/python3.6/site-packages/torch/_tensor_str.py", line 241, in _tensor_str
    formatter = _Formatter(get_summarized_data(self) if summarize else self)
  File "/opt/conda/envs/testgpu3/lib/python3.6/site-packages/torch/_tensor_str.py", line 89, in __init__
    nonzero_finite_vals = torch.masked_select(tensor_view, torch.isfinite(tensor_view) & tensor_view.ne(0))
RuntimeError: CUDA error: no kernel image is available for execution on the device
```

**Comment by truatpasteurdotfr** [comment]
upgrading cuda version to 11.3: no go as python3.6 does not have pytorch with CUDA built in.

**Comment by truatpasteurdotfr** [comment]
relaxing python requirement from 3.6 to default -> fixed
